# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d55b40efc48db58ec5653ef214b137a7a2a4adeeb3f6119fe8ff47360f8d7e6aeccf6ae92411f9bb1b590f1b10ee3a7f4b9f60c216a24c0cfbd85360a9db85f

test:
  secret_key_base: 360deadf7b8a3b2b9f4762e7bbd130e3b3d6173f535da1c5fc4ee5000614402c2419038806d45140f04c20fa983806e003d1076186a520026b5d15b9148047ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
